# Generated by Django 5.0.6 on 2024-07-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
